### ISSUE TITLE
Enhancing recommendations by classifications

### ISSUE THREAD

**Issue by srivkrnt** [OpenGenus/memes#119]
I was thinking of enhancing the way recommendations are generated, right now recommendations are generated based on the description and their location that is not a correct measure of how close two memes/images are in terms of similarity to be recommended.
I suggest image classification as a solution.

# Example
![Untitled](https://user-images.githubusercontent.com/23142350/54181179-b5262c00-44c3-11e9-96c0-4b4dbedf2e8a.png)
Taking up tags from this type of API can help us store them in the description json of the memes and these tags can be used for calculating the matchScore in recommendation.py 

Another way is generating these classifications locally using the tensorflow or similar tools/frameworks with pre-trained models. This will eliminate online dependency.

Please share your approaches and thoughts to solve this problem.

**Comment by srivkrnt** [comment]
I have added the classification API into utilities service. It returns tags for the passed image. If someone is interested then he/she can make changes to recommendation service to incorporate the classification score for Image match.

**Comment by teeniv001** [comment]
@srivkrnt claiming this issue .

**Comment by srivkrnt** [comment]
@teeniv001 I suggest you to replace the score that was computed using the path of meme with the image tag similarity score.
