### ISSUE TITLE
Abstraction : Restructuring project

### ISSUE THREAD

**Issue by srivkrnt** [OpenGenus/memes#124]
I suggest restructuring the project.
We have a setup.py file that can interact with all other files for a successful installation and therefore we can hide irrelevant details(Files) from a user installing the package. 
A new structure could be .

| root dir 
- A folder ```___``` (Some relevant name) containing all the data files, logos and other content files.
- A folder ```services``` that can contain all the services like recommendation, meme_generator, searchp etc.
- setup.py

After this we are left with only relevant folder in the root dir of the project and we need to modify module and file imports to support the structure.

Please have a look and claim this issue if you wish to work on this.

**Comment by teeniv001** [comment]
@AdiChat @srivkrnt 
I am claiming this issue.

**Comment by srivkrnt** [comment]
@teeniv001 
Sure Vineet, You may work on this.
