### ISSUE TITLE
Platform changes causing an error.

### ISSUE THREAD

**Issue by ulshell** [OpenGenus/memes#125]
One needs to modify files of index_data.py and recommendation just a small change of os.sep what it is returning in two of python 2 or 3 in Windows os as I am using Mac it is returning the same in both cases kindly see what it and if someone wants correct it.  I would suggest to make different files for both users as it will be ease for both users to work.

**Comment by srivkrnt** [comment]
@ulshell 
I wish to solve this using platform detection if that too fails we can think about using two files. I am claiming this issue for now.
