### ISSUE TITLE
Fix metadata generation directory.

### ISSUE THREAD

**Issue by srivkrnt** [OpenGenus/memes#138]
In one of the cases for meme_generation service, the metadata and probably the meme is not generated in the correct directory. The metadata and generated meme should be generated in the corresponding directory of the meme.

* Files to modify - [ ```services/meme_generation.py``` ]
* Expected point of issue = [ ``` use ``` routine ``` Line 20 to Line 33 ``` ]

Steps to reproduce :- 
``` openmemes --test=1 --module=generate ```

**Comment by teeniv001** [comment]
@srivkrnt wanted to fix this issue.

**Comment by srivkrnt** [comment]
@teeniv001 Sure you may work on this.
You can discuss things here in case of any confusion.

**Comment by teeniv001** [comment]
There is no problem with the metaData directory, it's created along with the corresponding generated meme but the cleanup procedure was failing to clean the metaData after the tests. 
I have fixed the cleanup procedure with #141

**Comment by srivkrnt** [comment]
@teeniv001 All right Vineet. Your changes look good. If there is no problem with the metadata generation then maybe one of the modes in the generation service create the meme in a different directory than the others but that's all right we can see that later.
